/*
 * stash-server
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1alpha1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * ComGithubAppscodeStashApisRepositoriesV1alpha1SnapshotStatus
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-04-09T00:59:16.508-07:00")
public class ComGithubAppscodeStashApisRepositoriesV1alpha1SnapshotStatus {
  @SerializedName("gid")
  private Integer gid = null;

  @SerializedName("hostname")
  private String hostname = null;

  @SerializedName("paths")
  private List<String> paths = new ArrayList<String>();

  @SerializedName("tree")
  private String tree = null;

  @SerializedName("uid")
  private Integer uid = null;

  @SerializedName("username")
  private String username = null;

  public ComGithubAppscodeStashApisRepositoriesV1alpha1SnapshotStatus gid(Integer gid) {
    this.gid = gid;
    return this;
  }

   /**
   * Get gid
   * @return gid
  **/
  @ApiModelProperty(required = true, value = "")
  public Integer getGid() {
    return gid;
  }

  public void setGid(Integer gid) {
    this.gid = gid;
  }

  public ComGithubAppscodeStashApisRepositoriesV1alpha1SnapshotStatus hostname(String hostname) {
    this.hostname = hostname;
    return this;
  }

   /**
   * Get hostname
   * @return hostname
  **/
  @ApiModelProperty(required = true, value = "")
  public String getHostname() {
    return hostname;
  }

  public void setHostname(String hostname) {
    this.hostname = hostname;
  }

  public ComGithubAppscodeStashApisRepositoriesV1alpha1SnapshotStatus paths(List<String> paths) {
    this.paths = paths;
    return this;
  }

  public ComGithubAppscodeStashApisRepositoriesV1alpha1SnapshotStatus addPathsItem(String pathsItem) {
    this.paths.add(pathsItem);
    return this;
  }

   /**
   * Get paths
   * @return paths
  **/
  @ApiModelProperty(required = true, value = "")
  public List<String> getPaths() {
    return paths;
  }

  public void setPaths(List<String> paths) {
    this.paths = paths;
  }

  public ComGithubAppscodeStashApisRepositoriesV1alpha1SnapshotStatus tree(String tree) {
    this.tree = tree;
    return this;
  }

   /**
   * Get tree
   * @return tree
  **/
  @ApiModelProperty(required = true, value = "")
  public String getTree() {
    return tree;
  }

  public void setTree(String tree) {
    this.tree = tree;
  }

  public ComGithubAppscodeStashApisRepositoriesV1alpha1SnapshotStatus uid(Integer uid) {
    this.uid = uid;
    return this;
  }

   /**
   * Get uid
   * @return uid
  **/
  @ApiModelProperty(required = true, value = "")
  public Integer getUid() {
    return uid;
  }

  public void setUid(Integer uid) {
    this.uid = uid;
  }

  public ComGithubAppscodeStashApisRepositoriesV1alpha1SnapshotStatus username(String username) {
    this.username = username;
    return this;
  }

   /**
   * Get username
   * @return username
  **/
  @ApiModelProperty(required = true, value = "")
  public String getUsername() {
    return username;
  }

  public void setUsername(String username) {
    this.username = username;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ComGithubAppscodeStashApisRepositoriesV1alpha1SnapshotStatus comGithubAppscodeStashApisRepositoriesV1alpha1SnapshotStatus = (ComGithubAppscodeStashApisRepositoriesV1alpha1SnapshotStatus) o;
    return Objects.equals(this.gid, comGithubAppscodeStashApisRepositoriesV1alpha1SnapshotStatus.gid) &&
        Objects.equals(this.hostname, comGithubAppscodeStashApisRepositoriesV1alpha1SnapshotStatus.hostname) &&
        Objects.equals(this.paths, comGithubAppscodeStashApisRepositoriesV1alpha1SnapshotStatus.paths) &&
        Objects.equals(this.tree, comGithubAppscodeStashApisRepositoriesV1alpha1SnapshotStatus.tree) &&
        Objects.equals(this.uid, comGithubAppscodeStashApisRepositoriesV1alpha1SnapshotStatus.uid) &&
        Objects.equals(this.username, comGithubAppscodeStashApisRepositoriesV1alpha1SnapshotStatus.username);
  }

  @Override
  public int hashCode() {
    return Objects.hash(gid, hostname, paths, tree, uid, username);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ComGithubAppscodeStashApisRepositoriesV1alpha1SnapshotStatus {\n");
    
    sb.append("    gid: ").append(toIndentedString(gid)).append("\n");
    sb.append("    hostname: ").append(toIndentedString(hostname)).append("\n");
    sb.append("    paths: ").append(toIndentedString(paths)).append("\n");
    sb.append("    tree: ").append(toIndentedString(tree)).append("\n");
    sb.append("    uid: ").append(toIndentedString(uid)).append("\n");
    sb.append("    username: ").append(toIndentedString(username)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

