/*
 * stash-server
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1alpha1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.IoK8sApiCoreV1ConfigMapProjection;
import io.swagger.client.model.IoK8sApiCoreV1DownwardAPIProjection;
import io.swagger.client.model.IoK8sApiCoreV1SecretProjection;
import java.io.IOException;

/**
 * Projection that may be projected along with other supported volume types
 */
@ApiModel(description = "Projection that may be projected along with other supported volume types")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-04-09T00:59:16.508-07:00")
public class IoK8sApiCoreV1VolumeProjection {
  @SerializedName("configMap")
  private IoK8sApiCoreV1ConfigMapProjection configMap = null;

  @SerializedName("downwardAPI")
  private IoK8sApiCoreV1DownwardAPIProjection downwardAPI = null;

  @SerializedName("secret")
  private IoK8sApiCoreV1SecretProjection secret = null;

  public IoK8sApiCoreV1VolumeProjection configMap(IoK8sApiCoreV1ConfigMapProjection configMap) {
    this.configMap = configMap;
    return this;
  }

   /**
   * information about the configMap data to project
   * @return configMap
  **/
  @ApiModelProperty(value = "information about the configMap data to project")
  public IoK8sApiCoreV1ConfigMapProjection getConfigMap() {
    return configMap;
  }

  public void setConfigMap(IoK8sApiCoreV1ConfigMapProjection configMap) {
    this.configMap = configMap;
  }

  public IoK8sApiCoreV1VolumeProjection downwardAPI(IoK8sApiCoreV1DownwardAPIProjection downwardAPI) {
    this.downwardAPI = downwardAPI;
    return this;
  }

   /**
   * information about the downwardAPI data to project
   * @return downwardAPI
  **/
  @ApiModelProperty(value = "information about the downwardAPI data to project")
  public IoK8sApiCoreV1DownwardAPIProjection getDownwardAPI() {
    return downwardAPI;
  }

  public void setDownwardAPI(IoK8sApiCoreV1DownwardAPIProjection downwardAPI) {
    this.downwardAPI = downwardAPI;
  }

  public IoK8sApiCoreV1VolumeProjection secret(IoK8sApiCoreV1SecretProjection secret) {
    this.secret = secret;
    return this;
  }

   /**
   * information about the secret data to project
   * @return secret
  **/
  @ApiModelProperty(value = "information about the secret data to project")
  public IoK8sApiCoreV1SecretProjection getSecret() {
    return secret;
  }

  public void setSecret(IoK8sApiCoreV1SecretProjection secret) {
    this.secret = secret;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IoK8sApiCoreV1VolumeProjection ioK8sApiCoreV1VolumeProjection = (IoK8sApiCoreV1VolumeProjection) o;
    return Objects.equals(this.configMap, ioK8sApiCoreV1VolumeProjection.configMap) &&
        Objects.equals(this.downwardAPI, ioK8sApiCoreV1VolumeProjection.downwardAPI) &&
        Objects.equals(this.secret, ioK8sApiCoreV1VolumeProjection.secret);
  }

  @Override
  public int hashCode() {
    return Objects.hash(configMap, downwardAPI, secret);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IoK8sApiCoreV1VolumeProjection {\n");
    
    sb.append("    configMap: ").append(toIndentedString(configMap)).append("\n");
    sb.append("    downwardAPI: ").append(toIndentedString(downwardAPI)).append("\n");
    sb.append("    secret: ").append(toIndentedString(secret)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

