# coding: utf-8

"""
    stash-server

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ComGithubAppscodeStashApisStashV1alpha1RestoreStats(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'duration': 'str',
        'path': 'str',
        'phase': 'str'
    }

    attribute_map = {
        'duration': 'duration',
        'path': 'path',
        'phase': 'phase'
    }

    def __init__(self, duration=None, path=None, phase=None):  # noqa: E501
        """ComGithubAppscodeStashApisStashV1alpha1RestoreStats - a model defined in Swagger"""  # noqa: E501

        self._duration = None
        self._path = None
        self._phase = None
        self.discriminator = None

        if duration is not None:
            self.duration = duration
        if path is not None:
            self.path = path
        if phase is not None:
            self.phase = phase

    @property
    def duration(self):
        """Gets the duration of this ComGithubAppscodeStashApisStashV1alpha1RestoreStats.  # noqa: E501


        :return: The duration of this ComGithubAppscodeStashApisStashV1alpha1RestoreStats.  # noqa: E501
        :rtype: str
        """
        return self._duration

    @duration.setter
    def duration(self, duration):
        """Sets the duration of this ComGithubAppscodeStashApisStashV1alpha1RestoreStats.


        :param duration: The duration of this ComGithubAppscodeStashApisStashV1alpha1RestoreStats.  # noqa: E501
        :type: str
        """

        self._duration = duration

    @property
    def path(self):
        """Gets the path of this ComGithubAppscodeStashApisStashV1alpha1RestoreStats.  # noqa: E501


        :return: The path of this ComGithubAppscodeStashApisStashV1alpha1RestoreStats.  # noqa: E501
        :rtype: str
        """
        return self._path

    @path.setter
    def path(self, path):
        """Sets the path of this ComGithubAppscodeStashApisStashV1alpha1RestoreStats.


        :param path: The path of this ComGithubAppscodeStashApisStashV1alpha1RestoreStats.  # noqa: E501
        :type: str
        """

        self._path = path

    @property
    def phase(self):
        """Gets the phase of this ComGithubAppscodeStashApisStashV1alpha1RestoreStats.  # noqa: E501


        :return: The phase of this ComGithubAppscodeStashApisStashV1alpha1RestoreStats.  # noqa: E501
        :rtype: str
        """
        return self._phase

    @phase.setter
    def phase(self, phase):
        """Sets the phase of this ComGithubAppscodeStashApisStashV1alpha1RestoreStats.


        :param phase: The phase of this ComGithubAppscodeStashApisStashV1alpha1RestoreStats.  # noqa: E501
        :type: str
        """

        self._phase = phase

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ComGithubAppscodeStashApisStashV1alpha1RestoreStats):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
