# coding: utf-8

"""
    stash-server

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.io_k8s_apimachinery_pkg_apis_meta_v1_time import IoK8sApimachineryPkgApisMetaV1Time  # noqa: F401,E501


class ComGithubAppscodeStashApisStashV1alpha1RepositoryStatus(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'backup_count': 'int',
        'first_backup_time': 'IoK8sApimachineryPkgApisMetaV1Time',
        'last_backup_duration': 'str',
        'last_backup_time': 'IoK8sApimachineryPkgApisMetaV1Time',
        'last_successful_backup_time': 'IoK8sApimachineryPkgApisMetaV1Time'
    }

    attribute_map = {
        'backup_count': 'backupCount',
        'first_backup_time': 'firstBackupTime',
        'last_backup_duration': 'lastBackupDuration',
        'last_backup_time': 'lastBackupTime',
        'last_successful_backup_time': 'lastSuccessfulBackupTime'
    }

    def __init__(self, backup_count=None, first_backup_time=None, last_backup_duration=None, last_backup_time=None, last_successful_backup_time=None):  # noqa: E501
        """ComGithubAppscodeStashApisStashV1alpha1RepositoryStatus - a model defined in Swagger"""  # noqa: E501

        self._backup_count = None
        self._first_backup_time = None
        self._last_backup_duration = None
        self._last_backup_time = None
        self._last_successful_backup_time = None
        self.discriminator = None

        if backup_count is not None:
            self.backup_count = backup_count
        if first_backup_time is not None:
            self.first_backup_time = first_backup_time
        if last_backup_duration is not None:
            self.last_backup_duration = last_backup_duration
        if last_backup_time is not None:
            self.last_backup_time = last_backup_time
        if last_successful_backup_time is not None:
            self.last_successful_backup_time = last_successful_backup_time

    @property
    def backup_count(self):
        """Gets the backup_count of this ComGithubAppscodeStashApisStashV1alpha1RepositoryStatus.  # noqa: E501


        :return: The backup_count of this ComGithubAppscodeStashApisStashV1alpha1RepositoryStatus.  # noqa: E501
        :rtype: int
        """
        return self._backup_count

    @backup_count.setter
    def backup_count(self, backup_count):
        """Sets the backup_count of this ComGithubAppscodeStashApisStashV1alpha1RepositoryStatus.


        :param backup_count: The backup_count of this ComGithubAppscodeStashApisStashV1alpha1RepositoryStatus.  # noqa: E501
        :type: int
        """

        self._backup_count = backup_count

    @property
    def first_backup_time(self):
        """Gets the first_backup_time of this ComGithubAppscodeStashApisStashV1alpha1RepositoryStatus.  # noqa: E501


        :return: The first_backup_time of this ComGithubAppscodeStashApisStashV1alpha1RepositoryStatus.  # noqa: E501
        :rtype: IoK8sApimachineryPkgApisMetaV1Time
        """
        return self._first_backup_time

    @first_backup_time.setter
    def first_backup_time(self, first_backup_time):
        """Sets the first_backup_time of this ComGithubAppscodeStashApisStashV1alpha1RepositoryStatus.


        :param first_backup_time: The first_backup_time of this ComGithubAppscodeStashApisStashV1alpha1RepositoryStatus.  # noqa: E501
        :type: IoK8sApimachineryPkgApisMetaV1Time
        """

        self._first_backup_time = first_backup_time

    @property
    def last_backup_duration(self):
        """Gets the last_backup_duration of this ComGithubAppscodeStashApisStashV1alpha1RepositoryStatus.  # noqa: E501


        :return: The last_backup_duration of this ComGithubAppscodeStashApisStashV1alpha1RepositoryStatus.  # noqa: E501
        :rtype: str
        """
        return self._last_backup_duration

    @last_backup_duration.setter
    def last_backup_duration(self, last_backup_duration):
        """Sets the last_backup_duration of this ComGithubAppscodeStashApisStashV1alpha1RepositoryStatus.


        :param last_backup_duration: The last_backup_duration of this ComGithubAppscodeStashApisStashV1alpha1RepositoryStatus.  # noqa: E501
        :type: str
        """

        self._last_backup_duration = last_backup_duration

    @property
    def last_backup_time(self):
        """Gets the last_backup_time of this ComGithubAppscodeStashApisStashV1alpha1RepositoryStatus.  # noqa: E501


        :return: The last_backup_time of this ComGithubAppscodeStashApisStashV1alpha1RepositoryStatus.  # noqa: E501
        :rtype: IoK8sApimachineryPkgApisMetaV1Time
        """
        return self._last_backup_time

    @last_backup_time.setter
    def last_backup_time(self, last_backup_time):
        """Sets the last_backup_time of this ComGithubAppscodeStashApisStashV1alpha1RepositoryStatus.


        :param last_backup_time: The last_backup_time of this ComGithubAppscodeStashApisStashV1alpha1RepositoryStatus.  # noqa: E501
        :type: IoK8sApimachineryPkgApisMetaV1Time
        """

        self._last_backup_time = last_backup_time

    @property
    def last_successful_backup_time(self):
        """Gets the last_successful_backup_time of this ComGithubAppscodeStashApisStashV1alpha1RepositoryStatus.  # noqa: E501


        :return: The last_successful_backup_time of this ComGithubAppscodeStashApisStashV1alpha1RepositoryStatus.  # noqa: E501
        :rtype: IoK8sApimachineryPkgApisMetaV1Time
        """
        return self._last_successful_backup_time

    @last_successful_backup_time.setter
    def last_successful_backup_time(self, last_successful_backup_time):
        """Sets the last_successful_backup_time of this ComGithubAppscodeStashApisStashV1alpha1RepositoryStatus.


        :param last_successful_backup_time: The last_successful_backup_time of this ComGithubAppscodeStashApisStashV1alpha1RepositoryStatus.  # noqa: E501
        :type: IoK8sApimachineryPkgApisMetaV1Time
        """

        self._last_successful_backup_time = last_successful_backup_time

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ComGithubAppscodeStashApisStashV1alpha1RepositoryStatus):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
