/*
 * stash-server
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1alpha1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.IoK8sApimachineryPkgApisMetaV1APIGroupList;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ApisApi
 */
@Ignore
public class ApisApiTest {

    private final ApisApi api = new ApisApi();

    
    /**
     * 
     *
     * get available API versions
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAPIVersionsTest() throws ApiException {
        IoK8sApimachineryPkgApisMetaV1APIGroupList response = api.getAPIVersions();

        // TODO: test validations
    }
    
}
