/*
 * stash-server
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1alpha1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.ComGithubAppscodeStashApisStashV1alpha1Recovery;
import io.swagger.client.model.ComGithubAppscodeStashApisStashV1alpha1RecoveryList;
import io.swagger.client.model.ComGithubAppscodeStashApisStashV1alpha1Restic;
import io.swagger.client.model.ComGithubAppscodeStashApisStashV1alpha1ResticList;
import io.swagger.client.model.IoK8sApimachineryPkgApisMetaV1APIResourceList;
import io.swagger.client.model.IoK8sApimachineryPkgApisMetaV1Status;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for StashAppscodeComV1alpha1Api
 */
@Ignore
public class StashAppscodeComV1alpha1ApiTest {

    private final StashAppscodeComV1alpha1Api api = new StashAppscodeComV1alpha1Api();

    
    /**
     * 
     *
     * delete a Recovery
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteStashAppscodeComV1alpha1NamespacedRecoveryTest() throws ApiException {
        String name = null;
        String namespace = null;
        String pretty = null;
        IoK8sApimachineryPkgApisMetaV1Status response = api.deleteStashAppscodeComV1alpha1NamespacedRecovery(name, namespace, pretty);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * delete a Restic
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteStashAppscodeComV1alpha1NamespacedResticTest() throws ApiException {
        String name = null;
        String namespace = null;
        String pretty = null;
        IoK8sApimachineryPkgApisMetaV1Status response = api.deleteStashAppscodeComV1alpha1NamespacedRestic(name, namespace, pretty);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * get available resources
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getStashAppscodeComV1alpha1APIResourcesTest() throws ApiException {
        IoK8sApimachineryPkgApisMetaV1APIResourceList response = api.getStashAppscodeComV1alpha1APIResources();

        // TODO: test validations
    }
    
    /**
     * 
     *
     * list objects of kind Recovery
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listStashAppscodeComV1alpha1NamespacedRecoveryTest() throws ApiException {
        String namespace = null;
        String _continue = null;
        String fieldSelector = null;
        Boolean includeUninitialized = null;
        String labelSelector = null;
        Integer limit = null;
        String pretty = null;
        String resourceVersion = null;
        Integer timeoutSeconds = null;
        Boolean watch = null;
        ComGithubAppscodeStashApisStashV1alpha1RecoveryList response = api.listStashAppscodeComV1alpha1NamespacedRecovery(namespace, _continue, fieldSelector, includeUninitialized, labelSelector, limit, pretty, resourceVersion, timeoutSeconds, watch);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * list objects of kind Restic
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listStashAppscodeComV1alpha1NamespacedResticTest() throws ApiException {
        String namespace = null;
        String _continue = null;
        String fieldSelector = null;
        Boolean includeUninitialized = null;
        String labelSelector = null;
        Integer limit = null;
        String pretty = null;
        String resourceVersion = null;
        Integer timeoutSeconds = null;
        Boolean watch = null;
        ComGithubAppscodeStashApisStashV1alpha1ResticList response = api.listStashAppscodeComV1alpha1NamespacedRestic(namespace, _continue, fieldSelector, includeUninitialized, labelSelector, limit, pretty, resourceVersion, timeoutSeconds, watch);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * list objects of kind Recovery
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listStashAppscodeComV1alpha1RecoveryForAllNamespacesTest() throws ApiException {
        String _continue = null;
        String fieldSelector = null;
        Boolean includeUninitialized = null;
        String labelSelector = null;
        Integer limit = null;
        String pretty = null;
        String resourceVersion = null;
        Integer timeoutSeconds = null;
        Boolean watch = null;
        ComGithubAppscodeStashApisStashV1alpha1RecoveryList response = api.listStashAppscodeComV1alpha1RecoveryForAllNamespaces(_continue, fieldSelector, includeUninitialized, labelSelector, limit, pretty, resourceVersion, timeoutSeconds, watch);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * list objects of kind Restic
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listStashAppscodeComV1alpha1ResticForAllNamespacesTest() throws ApiException {
        String _continue = null;
        String fieldSelector = null;
        Boolean includeUninitialized = null;
        String labelSelector = null;
        Integer limit = null;
        String pretty = null;
        String resourceVersion = null;
        Integer timeoutSeconds = null;
        Boolean watch = null;
        ComGithubAppscodeStashApisStashV1alpha1ResticList response = api.listStashAppscodeComV1alpha1ResticForAllNamespaces(_continue, fieldSelector, includeUninitialized, labelSelector, limit, pretty, resourceVersion, timeoutSeconds, watch);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * read the specified Recovery
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void readStashAppscodeComV1alpha1NamespacedRecoveryTest() throws ApiException {
        String name = null;
        String namespace = null;
        String pretty = null;
        ComGithubAppscodeStashApisStashV1alpha1Recovery response = api.readStashAppscodeComV1alpha1NamespacedRecovery(name, namespace, pretty);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * read the specified Restic
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void readStashAppscodeComV1alpha1NamespacedResticTest() throws ApiException {
        String name = null;
        String namespace = null;
        String pretty = null;
        ComGithubAppscodeStashApisStashV1alpha1Restic response = api.readStashAppscodeComV1alpha1NamespacedRestic(name, namespace, pretty);

        // TODO: test validations
    }
    
}
