# coding: utf-8

"""
    stash-server

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.com_github_appscode_stash_apis_stash_v1alpha1_s3_spec import ComGithubAppscodeStashApisStashV1alpha1S3Spec  # noqa: E501
from swagger_client.rest import ApiException


class TestComGithubAppscodeStashApisStashV1alpha1S3Spec(unittest.TestCase):
    """ComGithubAppscodeStashApisStashV1alpha1S3Spec unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testComGithubAppscodeStashApisStashV1alpha1S3Spec(self):
        """Test ComGithubAppscodeStashApisStashV1alpha1S3Spec"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.com_github_appscode_stash_apis_stash_v1alpha1_s3_spec.ComGithubAppscodeStashApisStashV1alpha1S3Spec()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
