# coding: utf-8

"""
    stash-server

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.repositories_stash_appscode_com_v1alpha1_api import RepositoriesStashAppscodeComV1alpha1Api  # noqa: E501
from swagger_client.rest import ApiException


class TestRepositoriesStashAppscodeComV1alpha1Api(unittest.TestCase):
    """RepositoriesStashAppscodeComV1alpha1Api unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.repositories_stash_appscode_com_v1alpha1_api.RepositoriesStashAppscodeComV1alpha1Api()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_repositories_stash_appscode_com_v1alpha1_namespaced_snapshot(self):
        """Test case for create_repositories_stash_appscode_com_v1alpha1_namespaced_snapshot

        """
        pass

    def test_delete_repositories_stash_appscode_com_v1alpha1_collection_namespaced_snapshot(self):
        """Test case for delete_repositories_stash_appscode_com_v1alpha1_collection_namespaced_snapshot

        """
        pass

    def test_delete_repositories_stash_appscode_com_v1alpha1_namespaced_snapshot(self):
        """Test case for delete_repositories_stash_appscode_com_v1alpha1_namespaced_snapshot

        """
        pass

    def test_get_repositories_stash_appscode_com_v1alpha1_api_resources(self):
        """Test case for get_repositories_stash_appscode_com_v1alpha1_api_resources

        """
        pass

    def test_list_repositories_stash_appscode_com_v1alpha1_namespaced_snapshot(self):
        """Test case for list_repositories_stash_appscode_com_v1alpha1_namespaced_snapshot

        """
        pass

    def test_list_repositories_stash_appscode_com_v1alpha1_snapshot_for_all_namespaces(self):
        """Test case for list_repositories_stash_appscode_com_v1alpha1_snapshot_for_all_namespaces

        """
        pass

    def test_patch_repositories_stash_appscode_com_v1alpha1_namespaced_snapshot(self):
        """Test case for patch_repositories_stash_appscode_com_v1alpha1_namespaced_snapshot

        """
        pass

    def test_read_repositories_stash_appscode_com_v1alpha1_namespaced_snapshot(self):
        """Test case for read_repositories_stash_appscode_com_v1alpha1_namespaced_snapshot

        """
        pass

    def test_replace_repositories_stash_appscode_com_v1alpha1_namespaced_snapshot(self):
        """Test case for replace_repositories_stash_appscode_com_v1alpha1_namespaced_snapshot

        """
        pass

    def test_watch_repositories_stash_appscode_com_v1alpha1_namespaced_snapshot(self):
        """Test case for watch_repositories_stash_appscode_com_v1alpha1_namespaced_snapshot

        """
        pass

    def test_watch_repositories_stash_appscode_com_v1alpha1_namespaced_snapshot_list(self):
        """Test case for watch_repositories_stash_appscode_com_v1alpha1_namespaced_snapshot_list

        """
        pass

    def test_watch_repositories_stash_appscode_com_v1alpha1_snapshot_list_for_all_namespaces(self):
        """Test case for watch_repositories_stash_appscode_com_v1alpha1_snapshot_list_for_all_namespaces

        """
        pass


if __name__ == '__main__':
    unittest.main()
