# coding: utf-8

"""
    stash-server

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.stash_appscode_com_v1alpha1_api import StashAppscodeComV1alpha1Api  # noqa: E501
from swagger_client.rest import ApiException


class TestStashAppscodeComV1alpha1Api(unittest.TestCase):
    """StashAppscodeComV1alpha1Api unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.stash_appscode_com_v1alpha1_api.StashAppscodeComV1alpha1Api()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_stash_appscode_com_v1alpha1_namespaced_recovery(self):
        """Test case for create_stash_appscode_com_v1alpha1_namespaced_recovery

        """
        pass

    def test_create_stash_appscode_com_v1alpha1_namespaced_repository(self):
        """Test case for create_stash_appscode_com_v1alpha1_namespaced_repository

        """
        pass

    def test_create_stash_appscode_com_v1alpha1_namespaced_restic(self):
        """Test case for create_stash_appscode_com_v1alpha1_namespaced_restic

        """
        pass

    def test_delete_stash_appscode_com_v1alpha1_collection_namespaced_recovery(self):
        """Test case for delete_stash_appscode_com_v1alpha1_collection_namespaced_recovery

        """
        pass

    def test_delete_stash_appscode_com_v1alpha1_collection_namespaced_repository(self):
        """Test case for delete_stash_appscode_com_v1alpha1_collection_namespaced_repository

        """
        pass

    def test_delete_stash_appscode_com_v1alpha1_collection_namespaced_restic(self):
        """Test case for delete_stash_appscode_com_v1alpha1_collection_namespaced_restic

        """
        pass

    def test_delete_stash_appscode_com_v1alpha1_namespaced_recovery(self):
        """Test case for delete_stash_appscode_com_v1alpha1_namespaced_recovery

        """
        pass

    def test_delete_stash_appscode_com_v1alpha1_namespaced_repository(self):
        """Test case for delete_stash_appscode_com_v1alpha1_namespaced_repository

        """
        pass

    def test_delete_stash_appscode_com_v1alpha1_namespaced_restic(self):
        """Test case for delete_stash_appscode_com_v1alpha1_namespaced_restic

        """
        pass

    def test_get_stash_appscode_com_v1alpha1_api_resources(self):
        """Test case for get_stash_appscode_com_v1alpha1_api_resources

        """
        pass

    def test_list_stash_appscode_com_v1alpha1_namespaced_recovery(self):
        """Test case for list_stash_appscode_com_v1alpha1_namespaced_recovery

        """
        pass

    def test_list_stash_appscode_com_v1alpha1_namespaced_repository(self):
        """Test case for list_stash_appscode_com_v1alpha1_namespaced_repository

        """
        pass

    def test_list_stash_appscode_com_v1alpha1_namespaced_restic(self):
        """Test case for list_stash_appscode_com_v1alpha1_namespaced_restic

        """
        pass

    def test_list_stash_appscode_com_v1alpha1_recovery_for_all_namespaces(self):
        """Test case for list_stash_appscode_com_v1alpha1_recovery_for_all_namespaces

        """
        pass

    def test_list_stash_appscode_com_v1alpha1_repository_for_all_namespaces(self):
        """Test case for list_stash_appscode_com_v1alpha1_repository_for_all_namespaces

        """
        pass

    def test_list_stash_appscode_com_v1alpha1_restic_for_all_namespaces(self):
        """Test case for list_stash_appscode_com_v1alpha1_restic_for_all_namespaces

        """
        pass

    def test_patch_stash_appscode_com_v1alpha1_namespaced_recovery(self):
        """Test case for patch_stash_appscode_com_v1alpha1_namespaced_recovery

        """
        pass

    def test_patch_stash_appscode_com_v1alpha1_namespaced_repository(self):
        """Test case for patch_stash_appscode_com_v1alpha1_namespaced_repository

        """
        pass

    def test_patch_stash_appscode_com_v1alpha1_namespaced_restic(self):
        """Test case for patch_stash_appscode_com_v1alpha1_namespaced_restic

        """
        pass

    def test_read_stash_appscode_com_v1alpha1_namespaced_recovery(self):
        """Test case for read_stash_appscode_com_v1alpha1_namespaced_recovery

        """
        pass

    def test_read_stash_appscode_com_v1alpha1_namespaced_repository(self):
        """Test case for read_stash_appscode_com_v1alpha1_namespaced_repository

        """
        pass

    def test_read_stash_appscode_com_v1alpha1_namespaced_restic(self):
        """Test case for read_stash_appscode_com_v1alpha1_namespaced_restic

        """
        pass

    def test_replace_stash_appscode_com_v1alpha1_namespaced_recovery(self):
        """Test case for replace_stash_appscode_com_v1alpha1_namespaced_recovery

        """
        pass

    def test_replace_stash_appscode_com_v1alpha1_namespaced_repository(self):
        """Test case for replace_stash_appscode_com_v1alpha1_namespaced_repository

        """
        pass

    def test_replace_stash_appscode_com_v1alpha1_namespaced_restic(self):
        """Test case for replace_stash_appscode_com_v1alpha1_namespaced_restic

        """
        pass

    def test_watch_stash_appscode_com_v1alpha1_namespaced_recovery(self):
        """Test case for watch_stash_appscode_com_v1alpha1_namespaced_recovery

        """
        pass

    def test_watch_stash_appscode_com_v1alpha1_namespaced_recovery_list(self):
        """Test case for watch_stash_appscode_com_v1alpha1_namespaced_recovery_list

        """
        pass

    def test_watch_stash_appscode_com_v1alpha1_namespaced_repository(self):
        """Test case for watch_stash_appscode_com_v1alpha1_namespaced_repository

        """
        pass

    def test_watch_stash_appscode_com_v1alpha1_namespaced_repository_list(self):
        """Test case for watch_stash_appscode_com_v1alpha1_namespaced_repository_list

        """
        pass

    def test_watch_stash_appscode_com_v1alpha1_namespaced_restic(self):
        """Test case for watch_stash_appscode_com_v1alpha1_namespaced_restic

        """
        pass

    def test_watch_stash_appscode_com_v1alpha1_namespaced_restic_list(self):
        """Test case for watch_stash_appscode_com_v1alpha1_namespaced_restic_list

        """
        pass

    def test_watch_stash_appscode_com_v1alpha1_recovery_list_for_all_namespaces(self):
        """Test case for watch_stash_appscode_com_v1alpha1_recovery_list_for_all_namespaces

        """
        pass

    def test_watch_stash_appscode_com_v1alpha1_repository_list_for_all_namespaces(self):
        """Test case for watch_stash_appscode_com_v1alpha1_repository_list_for_all_namespaces

        """
        pass

    def test_watch_stash_appscode_com_v1alpha1_restic_list_for_all_namespaces(self):
        """Test case for watch_stash_appscode_com_v1alpha1_restic_list_for_all_namespaces

        """
        pass


if __name__ == '__main__':
    unittest.main()
