# coding: utf-8

"""
    stash-server

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.com_github_appscode_stash_apis_repositories_v1alpha1_snapshot import ComGithubAppscodeStashApisRepositoriesV1alpha1Snapshot  # noqa: E501
from swagger_client.rest import ApiException


class TestComGithubAppscodeStashApisRepositoriesV1alpha1Snapshot(unittest.TestCase):
    """ComGithubAppscodeStashApisRepositoriesV1alpha1Snapshot unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testComGithubAppscodeStashApisRepositoriesV1alpha1Snapshot(self):
        """Test ComGithubAppscodeStashApisRepositoriesV1alpha1Snapshot"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.com_github_appscode_stash_apis_repositories_v1alpha1_snapshot.ComGithubAppscodeStashApisRepositoriesV1alpha1Snapshot()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
