# coding: utf-8

"""
    stash-server

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.stash_appscode_com_api import StashAppscodeComApi  # noqa: E501
from swagger_client.rest import ApiException


class TestStashAppscodeComApi(unittest.TestCase):
    """StashAppscodeComApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.stash_appscode_com_api.StashAppscodeComApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_stash_appscode_com_api_group(self):
        """Test case for get_stash_appscode_com_api_group

        """
        pass


if __name__ == '__main__':
    unittest.main()
