# coding: utf-8

"""
    stash-server

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.repositories_stash_appscode_com_api import RepositoriesStashAppscodeComApi  # noqa: E501
from swagger_client.rest import ApiException


class TestRepositoriesStashAppscodeComApi(unittest.TestCase):
    """RepositoriesStashAppscodeComApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.repositories_stash_appscode_com_api.RepositoriesStashAppscodeComApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_repositories_stash_appscode_com_api_group(self):
        """Test case for get_repositories_stash_appscode_com_api_group

        """
        pass


if __name__ == '__main__':
    unittest.main()
